### ISSUE TITLE
Refactoring: create Base class

### ISSUE THREAD

**Issue by pwilkins** [mitodl/PyLmod#10]
Refactor StellarGradebook class into a Base class containing code common to the new Gradebook and Membership classes.
@pdpinch @carsongee

**Comment by pwilkins** [comment]
I'm unfamiliar with the life-cycle of Python objects.  I wonder specifically how the invocation of the Base class methods by inheritance affects their scope.  Is there anything I need consider so that Python destroys these objects?

**Comment by Ferdi** [comment]
@pwilkins  you already have things set up.  

- Rename the StellarGradebook class to some [baseclassname]
- Rename the Client class to some specific (e.g. gradebook) name
- Add a new class "membership" similar to gradebook

**Comment by carsongee** [comment]
I think it would be worth making a list of the methods and which class they will end up in (i.e. Base, Membership and GradeBook), but it is probably easier to review that in code with the diff.  I also don't think you can actually split this up effectively into three different PRs since they are all super dependent, and you will want to do the whole refactor as one PR

**Comment by pwilkins** [comment]
This code from StellarGradebook could go to Base class:
https://github.com/mitodl/PyLmod/blob/master/pylmod/stellargradebook.py#L19-L162
